# Generated by Django 5.2.7 on 2025-10-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamescope_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the game (e.g., poster).', null=True, upload_to='games/covers/'),
        ),
    ]
